# Generated by Django 2.2 on 2019-04-07 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MediaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alternate_title', models.CharField(max_length=255)),
                ('volumes', models.IntegerField(default=0)),
                ('is_completed', models.BooleanField(default=False)),
                ('url', models.URLField()),
                ('interest', models.IntegerField()),
                ('notes', models.TextField()),
            ],
        ),
    ]
