# Generated by Django 2.2 on 2019-05-09 01:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    replaces = [('media_list', '0001_initial'), ('media_list', '0002_auto_20190406_2215'), ('media_list', '0003_mediaseries_has_omnibus'), ('media_list', '0004_mediaseries_status'), ('media_list', '0005_auto_20190410_2222'), ('media_list', '0006_auto_20190410_2255'), ('media_list', '0007_auto_20190413_1834'), ('media_list', '0008_auto_20190413_1856'), ('media_list', '0009_auto_20190414_2145'), ('media_list', '0010_auto_20190414_2227'), ('media_list', '0011_mediaseries_source'), ('media_list', '0012_auto_20190420_1617'), ('media_list', '0013_auto_20190501_1907'), ('media_list', '0014_auto_20190504_1817'), ('media_list', '0015_auto_20190508_2250')]

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='MangaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='BakaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baka_id', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(blank=True, max_length=255)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('original_publisher', models.CharField(blank=True, max_length=255)),
                ('english_publisher', models.CharField(blank=True, max_length=255)),
                ('image', models.ImageField(blank=True, null=True, upload_to='manga_images/')),
                ('genres', models.ManyToManyField(related_name='series', to='media_list.MangaGenre')),
                ('artists', models.ManyToManyField(related_name='series_as_artist', to='media_list.MangaPerson')),
                ('authors', models.ManyToManyField(related_name='series_as_author', to='media_list.MangaPerson')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MangaSource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to='source_icons/')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MediaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('alternate_title', models.CharField(blank=True, max_length=255)),
                ('volumes', models.IntegerField(blank=True, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('interest', models.IntegerField()),
                ('notes', models.TextField(blank=True)),
                ('has_omnibus', models.BooleanField(default=False)),
                ('status', models.CharField(choices=[('U', 'Unknown'), ('N', 'Not Downloaded'), ('D', 'Downloading'), ('R', 'Downloaded Raw'), ('E', 'Edited')], default='U', max_length=1)),
                ('is_read', models.BooleanField(default=False)),
                ('baka_id', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('baka_info', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_list.BakaSeries')),
                ('source', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_list.MangaSource')),
                ('created_at', models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ('title',),
            },
        ),
        migrations.CreateModel(
            name='MangaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('url', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='media_list.MediaSeries')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
