# Generated by Django 2.2.4 on 2019-10-06 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaseries',
            name='status',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'Not Downloaded'), ('D', 'Downloading'), ('R', 'Downloaded Raw'), ('E', 'Edited Complete'), ('I', 'Edited Incomplete')], default='U', max_length=1),
        ),
    ]
