# Generated by Django 2.2 on 2019-04-07 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaseries',
            name='alternate_title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='mediaseries',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='mediaseries',
            name='url',
            field=models.URLField(blank=True),
        ),
    ]
