# Generated by Django 2.2 on 2019-04-07 16:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0002_auto_20190406_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaseries',
            name='has_omnibus',
            field=models.BooleanField(default=False),
        ),
    ]
