# Generated by Django 2.2.8 on 2019-12-31 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0003_auto_20191225_2113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mangaserieskeyword',
            name='score',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
