# Generated by Django 2.2 on 2019-04-07 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0003_mediaseries_has_omnibus'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaseries',
            name='status',
            field=models.CharField(choices=[('N', 'Not Downloaded'), ('D', 'Downloading'), ('R', 'Downloaded Raw'), ('E', 'Edited')], default='N', max_length=1),
        ),
    ]
