# Generated by Django 2.2 on 2019-04-11 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0004_mediaseries_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='BakaSeries',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('baka_id', models.PositiveSmallIntegerField()),
                ('title', models.CharField(max_length=255)),
                ('genre', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('artist', models.CharField(max_length=255)),
                ('year', models.PositiveSmallIntegerField()),
                ('original_publisher', models.CharField(max_length=255)),
                ('english_publisher', models.CharField(max_length=255)),
            ],
        ),
        migrations.AlterModelOptions(
            name='mediaseries',
            options={'ordering': ['title']},
        ),
        migrations.AddField(
            model_name='mediaseries',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='mediaseries',
            name='source',
            field=models.CharField(choices=[('C', 'CRG'), ('E', 'Empire'), ('S', 'Scanlation'), ('O', 'Other')], default='O', max_length=1),
        ),
    ]
