# Generated by Django 2.2 on 2019-04-11 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0005_auto_20190410_2222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaseries',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
