# Generated by Django 2.2.8 on 2020-01-19 18:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_list', '0005_auto_20200101_2000'),
    ]

    operations = [
        migrations.CreateModel(
            name='IMDBMovie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('year', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('imdb_id', models.PositiveSmallIntegerField()),
                ('runtime', models.DurationField(blank=True, null=True)),
                ('rating', models.DecimalField(decimal_places=1, max_digits=3)),
                ('image', models.ImageField(blank=True, null=True, upload_to='movie_images/')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoKeyword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VideoPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('imdb_id', models.PositiveSmallIntegerField()),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AlterModelOptions(
            name='mangasource',
            options={},
        ),
        migrations.AlterModelOptions(
            name='videosource',
            options={},
        ),
        migrations.CreateModel(
            name='MoviePlot',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('text', models.TextField(blank=True)),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plots',
                                            to='media_list.IMDBMovie')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MovieCastMember',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('role', models.CharField(max_length=255, unique=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='media_list.VideoPerson')),
                ('movie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ordered_cast',
                                            to='media_list.IMDBMovie')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='cast',
            field=models.ManyToManyField(related_name='movies_as_cast', through='media_list.MovieCastMember',
                                         to='media_list.VideoPerson'),
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='countries',
            field=models.ManyToManyField(related_name='movies', to='media_list.VideoCountry'),
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='directors',
            field=models.ManyToManyField(related_name='movies_as_director', to='media_list.VideoPerson'),
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='genres',
            field=models.ManyToManyField(related_name='movies', to='media_list.VideoGenre'),
        ),
        migrations.AddField(
            model_name='imdbmovie',
            name='keywords',
            field=models.ManyToManyField(related_name='movies', to='media_list.VideoKeyword'),
        ),
    ]
