# Generated by Django 2.2.8 on 2020-01-20 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_list', '0006_auto_20200119_1558'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='imdb_info',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    to='media_list.IMDBMovie'),
        ),
    ]
