# Generated by Django 2.2 on 2019-04-13 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0006_auto_20190410_2255'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaGenre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
            },
        ),
        migrations.AlterModelOptions(
            name='mediaseries',
            options={'ordering': ('title',)},
        ),
        migrations.RemoveField(
            model_name='bakaseries',
            name='genre',
        ),
        migrations.AddField(
            model_name='bakaseries',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='manga_images/'),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='artist',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='author',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='english_publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='original_publisher',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='status',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='year',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bakaseries',
            name='genres',
            field=models.ManyToManyField(related_name='series', to='media_list.MangaGenre'),
        ),
    ]
