# Generated by Django 2.2 on 2019-04-13 21:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0007_auto_20190413_1834'),
    ]

    operations = [
        migrations.CreateModel(
            name='MangaPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'ordering': ('name',),
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='artist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_as_artist', to='media_list.MangaPerson'),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='series_as_author', to='media_list.MangaPerson'),
        ),
    ]
