# Generated by Django 2.2.8 on 2020-01-22 23:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_list', '0008_auto_20200122_1203'),
    ]

    operations = [
        migrations.AddField(
            model_name='imdbmovie',
            name='original_title',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
