# Generated by Django 2.2 on 2019-04-15 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0009_auto_20190414_2145'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaseries',
            name='source',
        ),
        migrations.AlterField(
            model_name='mediaseries',
            name='volumes',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
