# Generated by Django 4.2.2 on 2023-06-29 01:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('media_list', '0010_auto_20230619_1158'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='mangaurl',
            options={'ordering': ('order',)},
        ),
        migrations.AlterModelOptions(
            name='movieurl',
            options={'ordering': ('order',)},
        ),
        migrations.AddField(
            model_name='bakaseries',
            name='baka_code',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AddField(
            model_name='mangaseries',
            name='baka_code',
            field=models.CharField(blank=True, max_length=63, null=True),
        ),
        migrations.AlterField(
            model_name='bakaseries',
            name='baka_id',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='bakaseries',
            constraint=models.CheckConstraint(
                check=models.Q(('baka_id__isnull', False), ('baka_code__isnull', False), _connector='OR'),
                name='id_and_code_not_both_null',
                violation_error_message='Fields baka_id and baka_code cannot be both null.'),
        ),
    ]
