# Generated by Django 2.2 on 2019-04-15 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0010_auto_20190414_2227'),
    ]

    operations = [
        migrations.AddField(
            model_name='mediaseries',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='media_list.MangaSource'),
        ),
    ]
