# Generated by Django 2.2 on 2019-04-20 19:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0011_mediaseries_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mediaseries',
            name='status',
            field=models.CharField(choices=[('U', 'Unknown'), ('N', 'Not Downloaded'), ('D', 'Downloading'), ('R', 'Downloaded Raw'), ('E', 'Edited')], default='U', max_length=1),
        ),
    ]
