# Generated by Django 2.2 on 2019-05-01 22:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('media_list', '0012_auto_20190420_1617'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mediaseries',
            name='url',
        ),
        migrations.CreateModel(
            name='MangaURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(db_index=True, editable=False, verbose_name='order')),
                ('url', models.URLField()),
                ('series', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='urls', to='media_list.MediaSeries')),
            ],
            options={
                'ordering': ('order',),
                'abstract': False,
            },
        ),
    ]
